dist: bionic
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - make develop
# command to run tests
script:
  - make test_coverage
# to upload code coverage
after_success:
  - codecov
